# Generated by Django 4.0.4 on 2022-05-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('lastname', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phonenum', models.CharField(max_length=17)),
                ('dateofbirth', models.DateField()),
                ('cv', models.FileField(upload_to='media')),
            ],
        ),
    ]
